### ISSUE TITLE
panic: invalid argument to Intn

### ISSUE THREAD

**Issue by xyproto** [fogleman/pixsort#1]
Hi,

I know this is still probably under development, but I wanted to try it out. :)

Here's what I got:

```
$ pixsort image.png
0
0
panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0xc82000e2c0, 0x0, 0x45d34f)
    /usr/lib/go/src/math/rand/rand.go:98 +0x79
math/rand.Intn(0x0, 0x0)
    /usr/lib/go/src/math/rand/rand.go:198 +0x2d
github.com/fogleman/pixsort/pixsort.(*Model).DoMove(0xc820012240, 0x0, 0x0)
    /home/afr/go/src/github.com/fogleman/pixsort/pixsort/model.go:48 +0x4b
github.com/fogleman/pixsort/pixsort.Anneal(0x7f5830681828, 0xc820012240, 0x4059000000000000, 0x3fb999999999999a, 0x5f5e100, 0x0, 0x0)
    /home/afr/go/src/github.com/fogleman/pixsort/pixsort/anneal.go:24 +0x153
github.com/fogleman/pixsort/pixsort.Run(0x7ffe672a88c8, 0x24)
    /home/afr/go/src/github.com/fogleman/pixsort/pixsort/run.go:17 +0x361
main.main()
    /home/afr/go/src/github.com/fogleman/pixsort/main.go:10 +0x3d
```

**Comment by fogleman** [comment]
The image should be black and white pixels, like monochrome pixel art.

**Comment by xyproto** [comment]
When using a bw png image, it works! The result is fun. :)
